### ISSUE TITLE
JavaScript : Uncaught ReferenceError 오류가 발생했습니다

### ISSUE THREAD

**Issue by k8805** [codingeverybody/gfhg#1]
아래와 같이 코드를 작성했습니다.
```
<script>
      console.log(confir);
    </script>
```
그런데 실행이 되지 않고 있습니다.
아래와 같은 오류 메시지가 출력되고 있습니다.
```
index.html:9 Uncaught ReferenceError: confir is not defined
    at index.html:9
```
Uncaught ReferenceError로 검색해 보았습니다만,
정확한 해결책을 찾지 못하고 있습니다.

**Comment by egoing** [comment]
confir이라는 기능은 존재하지 않습니다. 아마도 confirm을 이용하고 싶으셨던 것이 아닐까 싶습니다. 
아래와 같이 변경해보세요. 

<script>
      console.log(confirm);
    </script>
